### ISSUE TITLE
Escaped quotes are not parsed correctly

### ISSUE THREAD

**Issue by LBmaster001** [Romgrafist/Stringtable-Dayz-Editor#1]
I tried to load my stringtable.csv and notices, that double quotes, which is how you escape quotes in CSV are not handled properly.
this string in CSV `"Quote Start:""Here is in quotes"" quotes end"` should be parsed as `Quote Start:"Here is in quotes" quotes end`

this is the line from my stringtable.csv: `lb_enable_playerlist_info,"Enable PlayerList (default Toggle Keybind: ""U"")","Playerlist Aktivieren (Standard Key: ""U""","Enable PlayerList (default Toggle Keybind: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","Włącz listę graczy (domyślnie: U"")","Enable PlayerList (default Toggle Keybind: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","Habilitar Lista de jugadores (tecla por defecto: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","启用 玩家列表 (默认切换 按键: ""U"")","Enable PlayerList (default Toggle Keybind: ""U"")","启用 玩家列表 (默认切换 按键: ""U"")"`

**Comment by Romgrafist** [comment]
Thank you. I fix it in next version. At the moment, the program does not know how to use double quotes.

**Comment by Romgrafist** [comment]
Try this version https://github.com/Romgrafist/Stringtable-Dayz-Editor/releases/tag/stringtable
